"""ApprovalTestingWidget - Widget for testing deferred tool approval patterns.

This widget provides three tools with different approval requirements:
1. basic_tool - No approval needed
2. sensitive_tool - Always requires approval (requires_approval=True)
3. maybe_tool - Conditionally requires approval (raises ApprovalRequired)
"""

from typing import TYPE_CHECKING, Optional

from pydantic_ai import RunContext
from pydantic_ai.exceptions import ApprovalRequired
from pydantic_ai.toolsets import FunctionToolset

from chimera_core.threadprotocol.blueprint import ComponentConfig
from chimera_core.widget import Widget

if TYPE_CHECKING:
    from chimera_core.agent import Agent
    from chimera_core.protocols.step_context import StepContext


class ApprovalTestingWidget(Widget):
    """Widget for testing tool approval patterns.

    Provides three tools with different approval behaviors:
    - basic_tool: No approval required
    - sensitive_tool: Always requires approval
    - maybe_tool: Conditionally requires approval based on question content
    """

    # Component metadata
    # component_class_name auto-generated by PluginMeta as "core.widgets.approval_testing_widget.ApprovalTestingWidget"
    component_version = "1.0.0"

    def __init__(self):
        """Initialize the approval testing widget."""
        super().__init__()

    def get_toolset(self, ctx: "StepContext") -> Optional[FunctionToolset]:
        """Return tools for testing approval patterns.

        Args:
            ctx: Step context with state and deps

        Returns:
            FunctionToolset with approval testing tools
        """
        toolset = FunctionToolset()

        @toolset.tool
        async def basic_tool() -> str:
            """A basic tool that always works without approval. Returns the meaning of life.

            No arguments needed. Just call it!
            """
            return "the meaning of life is 42"

        @toolset.tool(requires_approval=True)
        async def sensitive_tool() -> str:
            """A sensitive tool that always requires user approval before execution.

            Provides a helpful item, but only after user approval.
            No arguments needed.
            """
            # When this executes, approval has already been granted
            return "It's dangerous to go alone, take this"

        @toolset.tool
        async def maybe_tool(ctx: RunContext, question: str) -> str:
            """A tool that may or may not require approval depending on the question.

            If the question contains the word 'maybe', it executes without approval.
            Otherwise, it requires user approval first.

            Args:
                question: The question to answer

            Returns:
                A maybe-ish answer
            """
            # Check if approval is needed
            if "maybe" not in question.lower() and not ctx.tool_call_approved:
                raise ApprovalRequired

            # If we get here, either "maybe" is in the question or approval was granted
            return "Hmm, quite possibly"

        @toolset.tool
        async def special_tool(ctx: RunContext) -> str:
            """A special tool with no arguments that always requires approval.

            Always requires user approval before execution. Has no parameters.
            When approved, activates a trap card!

            Returns:
                A Yu-Gi-Oh reference
            """
            # Always require approval (unless already approved)
            if not ctx.tool_call_approved:
                raise ApprovalRequired

            # If we get here, approval was granted
            return "You've just activated my trap card!"

        return toolset

    def _serialize_config(self) -> dict:
        """Serialize widget configuration to dict.

        Returns:
            Empty dict (no config needed for this widget)
        """
        return {}  # No config needed for this widget

    # Note: to_blueprint_config() inherited from BasePlugin

    @classmethod
    def from_blueprint_config(
        cls, config: ComponentConfig, agent: "Agent"
    ) -> "ApprovalTestingWidget":
        """Deserialize widget from blueprint configuration.

        Args:
            config: ComponentConfig from Blueprint
            agent: Agent instance that owns this widget

        Returns:
            New ApprovalTestingWidget instance
        """
        widget = cls()
        widget.instance_id = config.instance_id
        return widget
