"""FeedbackWidget - Allow agents to leave feedback about tools and experiences.

Provides a leave_feedback tool that agents can use to report issues, suggest improvements,
or document situations where tools/safeguards were too restrictive. Feedback is saved as
.txt files organized by agent and thread.
"""

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Literal, Optional

from pydantic_ai import FunctionToolset, RunContext

from chimera_core.agent import PAIDeps

if TYPE_CHECKING:
    from pydantic_graph.beta import StepContext

    from chimera_core.agent import Agent

from ..threadprotocol.blueprint import ComponentConfig
from ..widget import Widget


@dataclass
class FeedbackWidgetConfig:
    """Configuration for FeedbackWidget.

    This is the BlueprintT type - stored in BlueprintProtocol at Turn 0.
    """

    enabled: bool = True
    feedback_dir: str = "data/feedback"


class FeedbackWidget(Widget[FeedbackWidgetConfig]):
    """Widget that allows agents to leave feedback about their tools and experiences.

    Agents can use the leave_feedback tool to:
    - Report when tools don't work as expected
    - Suggest improvements to safeguards/limits
    - Document situations for developer review
    - Act as "beta testers" for their own tooling

    Feedback is saved to: data/feedback/{agent_id}/{timestamp}_{thread_id[:8]}.txt

    Type parameters:
    - FeedbackWidgetConfig: Turn 0 configuration (BlueprintT)
    """

    # Component metadata
    component_version = "1.0.0"  # Required - explicit versioning
    # component_class_name auto-generated by PluginMeta

    def __init__(self, feedback_dir: str = "data/feedback"):
        """Initialize FeedbackWidget.

        Args:
            feedback_dir: Directory to save feedback files (default: data/feedback)
        """
        super().__init__()
        self.enabled: bool = True
        self.feedback_dir: str = feedback_dir

    async def get_instructions(self, ctx) -> str:
        """Inject instructions about the leave_feedback tool.

        Args:
            ctx: Step context with state and deps

        Returns:
            Instructions string to be added to agent's system prompt
        """
        if not self.enabled:
            return ""

        return """
Feedback Tool Instructions:
- You have access to a `leave_feedback` tool for reporting issues or suggestions
- Use this when:
  * A tool doesn't work as you expected it should
  * Safeguards seem overly restrictive for the situation
  * You encounter unexpected behavior worth documenting
  * You have improvement suggestions for your tooling
- Be specific: what you tried, what happened, what you expected
- Keep feedback concise (1 paragraph) unless you have a really good reason for more detail
- You're acting as a beta tester for your own tools - help make them better!
"""

    def get_toolset(self, ctx: "StepContext") -> Optional[FunctionToolset]:
        """Provide the leave_feedback tool.

        Args:
            ctx: Step context with thread state and active agent

        Returns:
            FunctionToolset containing leave_feedback tool
        """
        if not self.enabled:
            return None

        toolset = FunctionToolset()

        @toolset.tool
        async def leave_feedback(
            ctx: "RunContext[PAIDeps]",
            content: str,
            context: str = "general",
            severity: Literal["info", "warning", "error"] = "info",
        ) -> str:
            """Leave feedback about tools, safeguards, or unexpected behavior.

            Use this to report issues, suggest improvements, or document situations
            that the developer should know about. Be specific about what you tried,
            what happened, and what you expected.

            Args:
                content: Your feedback (keep to 1 paragraph unless you have a really good reason)
                context: What triggered this feedback (e.g., tool name, operation type, or "general")
                severity: How important this is ("info", "warning", or "error")

            Returns:
                Confirmation that feedback was saved

            Examples:
                leave_feedback(
                    content="Tried to read a file but got 'access denied' even though it's in my working directory. Expected read access to all files in my workspace.",
                    context="read_file",
                    severity="warning"
                )

                leave_feedback(
                    content="The file size limit of 100KB prevented me from reading documentation that would have been helpful. Suggest increasing limit or adding pagination.",
                    context="read_file",
                    severity="info"
                )
            """
            return await self._save_feedback(
                content=content, context=context, severity=severity, ctx=ctx
            )

        return toolset

    async def _save_feedback(
        self, content: str, context: str, severity: str, ctx: "RunContext[PAIDeps]"
    ) -> str:
        """Save feedback to a .txt file.

        Args:
            content: Feedback text
            context: What triggered the feedback
            severity: Importance level
            ctx: Run context for accessing thread/agent info

        Returns:
            Success message with file path
        """
        # Get agent and thread info from context
        thread_id = str(ctx.deps.thread_id)
        agent_id = ctx.deps.active_agent or "unknown"
        agent_name = "Agent"  # We don't have agent name in PAIDeps yet, could add it or just use ID

        # Generate timestamp
        timestamp = datetime.now(timezone.utc)
        timestamp_str = timestamp.isoformat()
        timestamp_filename = timestamp.strftime("%Y%m%d_%H%M%S")

        # Create directory structure: data/feedback/{agent_id}/
        agent_dir = Path(self.feedback_dir) / agent_id
        agent_dir.mkdir(parents=True, exist_ok=True)

        # Create filename: {timestamp}_{thread_id[:8]}.txt
        filename = f"{timestamp_filename}_{thread_id[:8]}.txt"
        filepath = agent_dir / filename

        # Get blueprint info if available (fallback to "unknown")
        try:
            blueprint_name = getattr(ctx.state.active_space, "name", "unknown")
        except AttributeError:
            blueprint_name = "unknown"

        # Format feedback file content
        feedback_content = f"""Agent: {agent_name}
Thread: {thread_id}
Timestamp: {timestamp_str}
Severity: {severity}
Blueprint: {blueprint_name}
Context: {context}

Feedback:
{content}
"""

        # Write to file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(feedback_content)

        return f"Feedback saved to {filepath}. Thank you for helping improve the system!"

    # BlueprintProtocol Serialization

    def _serialize_config(self) -> dict:
        """Serialize widget configuration to dict.

        Returns:
            Config dict (JSON-serializable)
        """
        return {"enabled": self.enabled, "feedback_dir": self.feedback_dir}

    # Note: to_blueprint_config() inherited from BasePlugin (uses _serialize_config())

    @classmethod
    def from_blueprint_config(cls, config: ComponentConfig, agent: "Agent") -> "FeedbackWidget":
        """Deserialize widget instance from BlueprintProtocol format.

        Args:
            config: ComponentConfig with config dict
            agent: Agent instance that owns this widget

        Returns:
            FeedbackWidget instance
        """
        widget = cls(feedback_dir=config.config.get("feedback_dir", "data/feedback"))
        widget.instance_id = config.instance_id
        widget.enabled = config.config.get("enabled", True)
        return widget
