"""QAWidget - Test widget for verifying widget infrastructure.

Provides a simple print_console tool and injects instructions with a secret number
to verify that widget instructions and tools are properly integrated.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from pydantic_graph.beta import StepContext

    from chimera_core.agent import Agent

from pydantic_ai import FunctionToolset

from ..threadprotocol.blueprint import ComponentConfig
from ..widget import Widget


@dataclass
class QAWidgetConfig:
    """Configuration for QAWidget.

    This is the BlueprintT type - stored in BlueprintProtocol at Turn 0.
    """

    enabled: bool = True


class QAWidget(Widget[QAWidgetConfig]):
    """Test widget that provides print_console tool and verifiable instructions.

    This widget serves as a simple test case to verify:
    1. Instruction injection works (via the secret number)
    2. Tool provision works (via print_console)
    3. Blueprint serialization/deserialization works

    Type parameters:
    - QAWidgetConfig: Turn 0 configuration (BlueprintT)
    - Any: No runtime mutations (MutationT) - this is a stateless widget
    """

    # Component metadata
    # component_class_name auto-generated by PluginMeta as "core.widgets.QAWidget"
    component_version = "1.0.0"  # Required - explicit versioning

    def __init__(self):
        """Initialize QAWidget."""
        super().__init__()
        self.enabled: bool = True

    async def get_instructions(self, ctx) -> str:
        """Inject instructions with secret number for verification.

        This method is called by Agent during setup to collect instructions
        from all widgets. The secret number verifies that instructions are
        actually being injected.

        Args:
            ctx: Step context with state and deps

        Returns:
            Instructions string to be added to agent's system prompt
        """
        if not self.enabled:
            return None

        return """
QA Widget Instructions:
- You have access to a print_console tool that prints messages to the console
- Use it to output debug information or important messages
- The secret number is 2341
"""

    def get_toolset(self, ctx: "StepContext") -> Optional[FunctionToolset]:
        """Provide the print_console tool.

        This method is called by Agent during setup to collect tools
        from all widgets.

        Args:
            ctx: Step context (for consistency with other get_toolset implementations)

        Returns:
            FunctionToolset containing print_console tool
        """
        if not self.enabled:
            return None

        toolset = FunctionToolset()

        @toolset.tool
        def print_console(message: str) -> str:
            """Print a message to the console.

            Use this to output debug information or important messages
            that should be visible in the server logs.

            Args:
                message: The message to print

            Returns:
                Confirmation that the message was printed
            """
            print(f"[QAWidget Console]: {message}")
            return f"Printed to console: {message}"

        return toolset

    # BlueprintProtocol Serialization

    def _serialize_config(self) -> dict:
        """Serialize widget configuration to dict.

        Returns:
            Config dict (JSON-serializable)
        """
        return {"enabled": self.enabled}

    # Note: to_blueprint_config() inherited from BasePlugin (uses _serialize_config())

    @classmethod
    def from_blueprint_config(cls, config: ComponentConfig, agent: "Agent") -> "QAWidget":
        """Deserialize widget instance from BlueprintProtocol format.

        Args:
            config: ComponentConfig with config dict
            agent: Agent instance that owns this widget

        Returns:
            QAWidget instance
        """
        widget = cls()
        widget.instance_id = config.instance_id
        widget.enabled = config.config.get("enabled", True)
        return widget
